"""Generate `.cmux/setup` shim that translates .worktree-contract.json
at runtime when cmux invokes it.

Per docs/superpowers/specs/2026-05-01-orca-worktree-contract-design.md
§"cmux compatibility".
"""
from __future__ import annotations

import os
import stat
from pathlib import Path

_SHIM_BODY = '''\
#!/usr/bin/env bash
# Generated by orca-cli wt contract install-cmux-shim
# Translates .worktree-contract.json into cmux's setup convention.
# Do not edit -- re-run install-cmux-shim to refresh.
set -euo pipefail

command -v python3 >/dev/null 2>&1 || {
    echo "orca-cli wt contract shim requires python3 on PATH" >&2
    exit 1
}

# Trust warning (every invocation; CI bypasses via ORCA_SHIM_NO_PROMPT=1).
echo "WARNING: cmux shim runs init_script with no trust check." >&2
echo "  Hostile init_scripts in cloned repos run as your user." >&2
if [ -t 0 ] && [ "${ORCA_SHIM_NO_PROMPT:-0}" != "1" ]; then
    echo -n "  Press ENTER to continue, Ctrl-C to abort: " >&2
    read -r _
fi

REPO_ROOT="$(git rev-parse --git-common-dir | xargs dirname)"
CONTRACT="$REPO_ROOT/.worktree-contract.json"
if [[ ! -f "$CONTRACT" ]]; then
    echo ".worktree-contract.json not found; cmux shim is a no-op" >&2
    exit 0
fi

python3 - "$CONTRACT" "$REPO_ROOT" <<'PY'
import json, os, sys
contract_path, repo_root = sys.argv[1], sys.argv[2]
try:
    with open(contract_path) as f:
        c = json.load(f)
except Exception as e:
    print(f"contract parse failed: {e}", file=sys.stderr)
    sys.exit(0)

for rel in c.get("symlink_paths", []) + c.get("symlink_files", []):
    if rel.startswith("/") or ".." in rel.split("/"):
        print(f"contract: rejecting unsafe path {rel!r}", file=sys.stderr)
        continue
    src = os.path.join(repo_root, rel)
    if not os.path.exists(src):
        continue
    if os.path.lexists(rel) and not os.path.islink(rel):
        continue
    if os.path.lexists(rel):
        os.unlink(rel)
    parent = os.path.dirname(rel)
    if parent:
        os.makedirs(parent, exist_ok=True)
    os.symlink(src, rel)
PY

INIT_SCRIPT_REL="$(python3 - "$CONTRACT" <<'PY'
import json, sys
try:
    rel = json.load(open(sys.argv[1])).get('init_script') or ''
except Exception:
    sys.exit(0)
if rel.startswith('/') or '..' in rel.split('/'):
    print(f"contract: rejecting unsafe init_script path {rel!r}",
          file=sys.stderr)
    sys.exit(0)
print(rel)
PY
)"
if [[ -n "$INIT_SCRIPT_REL" ]]; then
    INIT_SCRIPT="$REPO_ROOT/$INIT_SCRIPT_REL"
    if [[ -x "$INIT_SCRIPT" ]]; then
        "$INIT_SCRIPT"
    fi
fi
'''


def install_cmux_shim(repo_root: Path, *, force: bool) -> Path:
    """Write `.cmux/setup` shim. Returns the path."""
    out_dir = repo_root / ".cmux"
    out = out_dir / "setup"
    if out.exists() and not force:
        raise FileExistsError(
            f"{out} already exists; pass force=True to overwrite"
        )
    out_dir.mkdir(parents=True, exist_ok=True)
    out.write_text(_SHIM_BODY, encoding="utf-8")
    out.chmod(out.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP)
    return out
