"""Ecosystem detection + after_create script generation for `wt init`.

v1: top-level signal files only. Subdirectory monorepos emit a warning.
"""
from __future__ import annotations

import os
import stat
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class EcosystemHit:
    name: str
    install_line: str | None  # None for warnings


_RULES: list[tuple[str, str, list[str]]] = [
    # (signal_file, ecosystem_name, install_command_words)
    ("uv.lock", "uv", ["uv", "sync"]),
    ("bun.lockb", "bun", ["bun", "install"]),
    ("pnpm-lock.yaml", "pnpm", ["pnpm", "install"]),
    ("yarn.lock", "yarn", ["yarn", "install"]),
    ("Cargo.toml", "cargo", ["cargo", "fetch"]),
    ("go.mod", "go", ["go", "mod", "download"]),
    ("Gemfile", "bundler", ["bundle", "install"]),
]


def detect_ecosystems(repo_root: Path) -> list[EcosystemHit]:
    """Top-level signal-file detection. Returns a list of EcosystemHit."""
    hits: list[EcosystemHit] = []
    seen_top_npm = (repo_root / "package.json").exists()

    for signal, name, install in _RULES:
        if (repo_root / signal).exists():
            hits.append(EcosystemHit(name=name, install_line=" ".join(install)))

    # node fallback: package.json + no specific lockfile -> npm install
    if seen_top_npm and not any(h.name in {"bun", "pnpm", "yarn"} for h in hits):
        hits.append(EcosystemHit(name="npm", install_line="npm install"))

    # pip via requirements*.txt (no pyproject)
    if not any(h.name == "uv" for h in hits):
        for req in sorted(repo_root.glob("requirements*.txt")):
            hits.append(EcosystemHit(name="pip",
                                     install_line=f"pip install -r {req.name}"))
            break  # one is enough; comment in script suggests editing

    # Monorepo warning
    for parent in ("apps", "packages", "crates"):
        if (repo_root / parent).is_dir():
            for child in (repo_root / parent).iterdir():
                if not child.is_dir():
                    continue
                if any((child / s).exists() for s, _, _ in _RULES) or \
                   (child / "package.json").exists():
                    hits.append(EcosystemHit(
                        name="monorepo_warning",
                        install_line=None,
                    ))
                    break

    return hits


def generate_after_create(
    repo_root: Path, *, replace: bool = False,
) -> Path:
    """Write a default after_create script. Refuses to overwrite unless
    `replace=True`. Returns the path."""
    out_dir = repo_root / ".orca" / "worktrees"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "after_create"
    if out_path.exists() and not replace:
        raise FileExistsError(f"{out_path} exists; pass replace=True to overwrite")

    hits = detect_ecosystems(repo_root)
    install_lines = [h.install_line for h in hits if h.install_line]
    has_warning = any(h.name == "monorepo_warning" for h in hits)

    body_parts = [
        "#!/usr/bin/env bash",
        "set -e",
        "",
        "# Generated by `orca-cli wt init`. Edit freely.",
        f"# Ecosystem detection found: "
        f"{', '.join(h.name for h in hits if h.install_line) or '(none)'}",
    ]
    if has_warning:
        body_parts.append(
            "# WARNING: monorepo signals detected in apps/, packages/, "
            "or crates/. Edit per-package install lines if needed."
        )
    body_parts.append("")
    if not install_lines:
        body_parts.append("# No ecosystems detected; this hook is a no-op.")
        body_parts.append("exit 0")
    else:
        for line in install_lines:
            body_parts.append(line)

    out_path.write_text("\n".join(body_parts) + "\n", encoding="utf-8")
    os.chmod(out_path, out_path.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)
    return out_path
